### PR TITLE
Fix 67: Universal pkgdown

### LINKED ISSUE #44: Update pkgdown github action to only run on PRs from Gilead-Biostats branches
## Current Behavior

Currently, when an outside contributor submits a PR to dev from their forked version of the repo, the pkgdown action breaks because there are not the proper permissions available to deploy the site.

## Possible Solution

Set the workflow triggers to be based on organization of origin

## Steps to Reproduce

See [this PR](https://github.com/Gilead-BioStats/gsm.kri/pull/167) for a discussion and example

## QC Approach

In addition to standard QC (e.g., code reviews, automated checks) the following QC measures will be implemented:

[ ] Update existing Qualification/Unit Tests 
[ ] New Unit Tests

### LINKED ISSUE #66: Consider bumping R compat version in GHA check templates (4.1.3 → 4.2+)
This Issue was drafted by GitHub Copilot using Claude Opus 4.6 and reviewed by @jwildfire

## Summary

The R-CMD-check GHA templates currently test against R 4.1.3 as the minimum compatibility version. Consider bumping this to R 4.2.3 or later.

## Context

While updating downstream repos (e.g., workr) to match the gsm.utils templates, we noticed workr had previously bumped its compat matrix to R 4.2.3. The current templates still use 4.1.3.

Affected templates:
- `inst/gha_templates/workflows/R-CMD-check-dev.yaml`
- `inst/gha_templates/workflows/R-CMD-check.yaml`

## Recommendation

Evaluate whether R >= 4.2 is a reasonable minimum across all gsm packages and bump the compat matrix accordingly.

### LINKED ISSUE #67: Reconcile pkgdown GHA
## Task Summary
Combine the various ways we've implemented slide decks in our GHA into a single preferred option.

## Problem / Rationale
Including a slide deck or slide decks in the site is useful. Let's have a process!

## Scope
This issue will involve sorting out this approach, but also "stabilizing" the pkgdown GHA in general a bit.

## Proposed Approach (Optional)
- [x] Review our existing pkgdown sites to find various ways in which slide decks are implemented.
- [x] Choose the one (or ones) that make the most sense.
- [x] Implement that reconciled GHA in gsm.utils.
- [x] Break up the gsm.utils pkgdown GHA into components.
- [x] Sort out any R updates that make sense to go with this change, and implement them.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Unify various ideas about examples and slide decks, and future-proof to allow us to automatically add additional menus.

## Test Notes/Sample Code
I've been testing this over in https://github.com/Gilead-BioStats/qcthat/pull/297 

We also should rebuild the `actions-v1` branch from `dev` once this is merged (and whenever actions change in non-breaking ways).

## Connected Issues

- Closes #67
- Closes #66 
- Closes #44

## IMPORTANT: To-do after merge

Unless we change this during review, these actions are all installed from a `actions-v1` branch. We should update that branch to match `dev`. It probably would make sense to create a GHA in this repo (in .github but NOT mirrored in inst) that automatically creates a PR to merge `dev` into `actions-v1` whenever the `actions` folder changes (I'd say just have it update it automatically, but that fails when we want to switch to a `actions-v2` version.

### CODE REVIEW

File: R/pkgdown-add_pkgdown_nav.R [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+#' @inheritParams build_assets_params
+#' @returns An updated list of pkgdown YAML contents with the new menu added.
+#' @keywords internal
+ensure_pkgdown_menu_section <- function(pkgdown_contents, menu) {
+  if (is.null(pkgdown_contents[["navbar"]][["components"]][[menu]])) {
+    pkgdown_contents[["navbar"]][["components"]][[menu]] <- list(
+      text = to_title_case(menu),
+      menu = list()
+    )
+  }
```
[the remark this answers is not in the document]
Comment (jonthegeek) [reply R/pkgdown-add_pkgdown_nav.R:78]: Incorrect. That's why I test that explicitly. R's smarter about this than you might think.

File: R/pkgdown-add_pkgdown_nav.R [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+#' @returns An updated list of pkgdown YAML contents with the new menu entries
+#'   added.
+#' @keywords internal
+update_pkgdown_menu <- function(
+  pkgdown_contents,
+  menu,
+  menu_subdir,
+  rendered_assets,
+  verbose
+) {
```
Comment (lauramaxwell) [inline R/pkgdown-add_pkgdown_nav.R:51]: Does this ensure we don't have duplicate menu items? So, if someone had hand edited the _pkgdown.yml would this handle that appropriately, or would it add to it? or just overwrite?

**Review by lauramaxwell — COMMENTED** [review]
One question about pkgdown menu, but other than that this is looking great!

File: R/pkgdown-add_pkgdown_nav.R (hunk 2 above)
Comment (jonthegeek) [reply R/pkgdown-add_pkgdown_nav.R:51]: Huh. Right now it deletes anything that's in the target `menu` but wasn't in `pkgdown/menus/{menu}`. Likewise, if *nothing* is defined in `pkgdown/menus/{menu}` but the directory exists (perhaps with just a `.gitignore` in it, for example), the menu will be removed.

I can add checks now to keep things that are already there and point at either a URL or a file path that exists. It's a little complicated to get that right, but I can do it. Should I do it in this PR, or should we create an issue and fix it when/if we have a mix of things defined in `pkgdown/menus` and things that aren't in there but belong in the same menu? Right now it feels easy to avoid that issue, but it's probably worth at least thinking about.

Comment (lauramaxwell) [reply R/pkgdown-add_pkgdown_nav.R:51]: Let's create an issue for it and tackle it down the line as we see fit. thanks!

**Review by lauramaxwell — APPROVED** [review]
LGTM!

File: R/pkgdown-add_pkgdown_nav.R (hunk 2 above)
Comment (jonthegeek) [reply R/pkgdown-add_pkgdown_nav.R:51]: Ticket: #79
